import requests
import csv
import config

"""This module is a simple program that takes a ZIP Code and a POI and finds the top 10 near the given ZIP Code."""

zip_code = input('Please enter a ZIP Code. ')
term = input('What do you want to search for near {0}? '.format(zip_code))

bus = []
final = []
url = 'https://api.yelp.com/v3/businesses/search'

headers = {
    'Authorization':'Bearer ' + config.api_key
}
#The api_key must be generated by each user.

params = {
    'term': term,
    "location": zip_code
}

response = requests.get(url, headers=headers, params=params)
businesses = response.json()['businesses']
for business in businesses:
    bus.append(business['name'])

for item in bus:
    final.append(item)

final = []
    

print('The top 10 {0} businesses near {1} are... : '.format(term, zip_code))
for item in bus[0:10]:
    print(item)

#This block writes the top 10 displayed on terminal to a CSV file for the end_user to reference to.
if bool(input('Do you want the response in a CSV? (Plz enter a Boolean True or False').lower) == 'true' :
    with open('businesses.csv', 'w+') as file:
        writer = csv.writer(file)
        writer.writerow(['Names:'])
        for item in bus[0:10]:
            writer.writerow([item])
        print('Succesfully wrote to {0}'.format(csv))  
else:
    pass